name: Use API Key

on:
  push:
    branches:
      - main

jobs:
  make-api-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use API Key
        run: |
          echo "Using API key: ${{ secrets.API_KEY }}"
        env:
          API_KEY: ${{ secrets.API_KEY }}