# nome do workflow
name: macOS Workflow Example

# evento
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest # runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Swift File
        run: |
          echo 'print("Hello from Swift on macOS")' > hello.swift

      - name: Install dependencies
        run: |
          brew install swiftlint # brew é gerenciador de pacotes do mac

      - name: Run SwiftLint
        run: swiftlint

      - name: Compile and run Swift program
        run: |
          swiftc hello.swift 
          ./hello