# esecuta segundo a "agenda abaixo"
# essa expressão cron significa executar o fluxo a cada 5 minutos
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  hello_world: # nome do job
    runs-on: ubuntu-latest # runner
    steps: # passo 1
      - name: Echo current time # nome do passo 1
        run: echo "The current server time is $(date)" # exibe variável de ambiente
